version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_SECRET_KEY=${VITE_SECRET_KEY}
      - VITE_IMAGE_URL=${VITE_IMAGE_URL}
      - VITE_API_KEY=${VITE_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    stdin_open: true
    tty: true